### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LordJoshie** [RevivalPMMP/PureEntitiesX#133]
You had a fork called 1.0.0 bug fixes, or something like that... I'm currently using it, it seems fine... but the master branch is messed up and throws a lot of bugs on Tesseract. 

Any way to ensure compatibility with Tesseract, or do you know of the branch I'm referring to?

**Comment by kniffo80** [comment]
Before this will get closed - you are not using issue template - just a few words on this.

Using other than PocketMine-MP is currently not really supported by us. I have a testserver running remotely which uses PocketMine-MP or Elywing together with the master branch of PureEntitiesX. I've not seen any issues regarding the plugin.

So, please use PocketMine-MP (the "original" software) together with PureEntitiesX. If you encounter any issues then, report back with a proper issue description and with some logoutput (if there is any).

I'm currently developing the Wolf AI - which just took my server down because of performance issues. The more AI is built in the slower the server gets. I'm currently working in parallel on performance of this plugin and additionally on the Wolf AI - so that wolves are completely tameable, can sit, hunt and support the owner then the owner gets attacked or the owner attacks an entity. This is a lot of checks and so on which just consumes a lot of performance. This is just for information :smile:

**Comment by LordJoshie** [comment]
Thanks, and that sounds cool


also, I wasn't reporting an issue... I was asking a question, and just
letting you know why I wasn't using the master branch.


Regardless, this is all very cool, and I look forward to seeing more
progress in the future.

Elywing isnt PMMP, and Tesseract is better than Elywing... so... why would
you use Ely over Tess, if using anything other than Pmmp...

:)

**Comment by kniffo80** [comment]
Thanks for reporting. Just stay tuned. Implementing Mob AI is not an easy one :relaxed:

**Comment by LordJoshie** [comment]
I'll certainly stay tuned. and check daily for updates. Ill test and report
when what Im using is relevant.

the branch im using had been deleted... so what I have is irrelevant.

but yeah, for those who are working on this project... good work, and keep
it up ! this is huge for pmmp

**Comment by jasonwynn10** [comment]
@kniffo80 if you look at the most recent travis build, there was an issue that travis put out

**Comment by kniffo80** [comment]
Will take a look asap

**Comment by kniffo80** [comment]
@jasonwynn10 as far as i can see, the travis build fails because the DevTools isn't compatible with the current PocketMine-MP API ... not by the Code of the plugin!

**Comment by jasonwynn10** [comment]
https://travis-ci.org/RevivalPMMP/PureEntitiesX/builds/200224579#L713

**Comment by kniffo80** [comment]
:thumbsup:

**Comment by archie426** [comment]
Anyways, please ask questions on our forums (Link in readme)
