### ISSUE TITLE
lag and more 

### ISSUE THREAD

**Issue by Emis02** [RevivalPMMP/PureEntitiesX#212]
this plugin tends to muddle the server at the despawn of the entities. giving the bones to the wolf the wolf gets married but does not collar and stays in infinity and there is no way to raise it. looking at the endermans nothing happens exactly what to beat them.

i have pmmp

**Comment by Emis02** [comment]
and all entities jump 2 block

**Comment by 95CivicSi** [comment]
It's important to separate the problems you are having into separate issues if they are not related.  For instance, if the lag is not caused by giving a bone to the wolf, then lag and wolf loyalty issues are not related.  Please open separate issues for Wolf Loyalty, Enderman interactions, and Entity Jump height.
Please provide the following information to help us recreate your problem.

Version of PocketMine-MP being used.

OS used to run PocketMine-MP including any significant Version number (eg. Ubuntu 16.04, Windows 10, macOS 10.13).

How you installed PocketMine-MP (including any control panels or wrappers).

How you installed PureEntitesX,

PureEntitesX Configuration File.

Any other known, relevant steps to reproduce the issue you are having.

Server Logs or CrashDumps that can show any related errors.
