### ISSUE TITLE
enderman

### ISSUE THREAD

**Issue by RubyTemple** [RevivalPMMP/PureEntitiesX#216]
looking at the endermans nothing happens exactly what to beat them.

**Comment by 95CivicSi** [comment]
Most recent updates to PureEntitiesX include a change in how the EndermanLooking task works.  Commit https://github.com/RevivalPMMP/PureEntitiesX/commit/7fe382fec26ee1f012d3d0744475ac6393aea43c and https://github.com/RevivalPMMP/PureEntitiesX/commit/ebe3f8a733baa57b0b118067c22a63b4fa3edd39 transition this to use `VoxelRayTrace` instead of `BlockIterator`.  New testing needs to be done to determine if this is still an issue.

**Comment by 95CivicSi** [comment]
If someone notices this issue or something similar in newer versions of PEX, feel free to open a new issue with related info.
