### ISSUE TITLE
Console spamming with this error

### ISSUE THREAD

**Issue by Antisa14200** [RevivalPMMP/PureEntitiesX#266]
[Server thread/CRITICAL]: Could not execute task revivalpmmp\pureentities\task\EndermanLookingTask: Class 'pocketmine\utils\BlockIterator' not found
[Server thread/CRITICAL]: Error: "Class 'pocketmine\utils\BlockIterator' not found" (EXCEPTION) in "PureEntitiesX-Jumping-Mobs/src/revivalpmmp/pureentities/InteractionHelper" at line 76

It's happening because since Pocketmine  https://jenkins.pmmp.io/job/PocketMine-MP/602/ update:
 "Kill BlockIterator, added a VoxelRayTrace class with level-independent generator functions" on commit 
https://github.com/pmmp/PocketMine-MP/commit/71d11c73f061babfdad3caf7a5331ea4acc63453

**Comment by jasonwynn10** [comment]
@95CivicSi Don't use bleeding edge. This type of error is the result.

**Comment by 95CivicSi** [comment]
@jasonwynn10, not sure why you tagged me in your comment. @Antisa14200, The released version of PureEntitiesX is targeted to work with the latest release of PocketMine-MP.
https://github.com/pmmp/PocketMine-MP/releases/tag/1.7dev-516.  

To resolve your issue, please install the compatible version of PocketMine-MP, otherwise, this will be resolved once the next API version is released.

**Comment by Antisa14200** [comment]
Oh okay then, thanks,

**Comment by llronaldoll** [comment]
![image](https://user-images.githubusercontent.com/5334591/34912947-03d04ba0-f8d6-11e7-8baa-821e09e154d8.png)

**Comment by Adam1609** [comment]
well you must make this plugin compatible, so everyone can use it, this is the public plugin ya know.
(well Im mad that they removed the BlockIterator)

**Comment by Antisa14200** [comment]
@95CivicSi is using Alpha versions only so that's why

**Comment by 95CivicSi** [comment]
I'm working on making that a little more clear in our documentation.  Right now its really hard to avoid conflicts like this due to how PocketMine-MP is updating it's API version numbers.

**Comment by Daniil129932** [comment]
I'm waiting for the update to build 625+!

**Comment by Alderander** [comment]
633 and still works in 95% :)
For now, I have isolated the pieces of code caused the problems and I waiting politely for corrections. The behavior of the animals only changed that they do not looks at the players, that's all. So far the rest works without problems. Why do not I install the old version 512? Because 'alpha' is fixed all the time and the list of patches and improvements is here https://jenkins.pmmp.io/job/PocketMine-MP/changes. I really do not want to go back only for one plugin :)
(sry for english, blame google trans.)

**Comment by Antisa14200** [comment]
Yeah

Dana 20. sij 2018. 03:50 osoba "Alderander" <notifications@github.com>
napisala je:

633 and still works in 95% :)
For now, I have isolated the pieces of code caused the problems and I
waiting politely for corrections. The behavior of the animals only changed
that they do not looks at the players, that's all. So far the rest works
without problems. Why do not I install the old version 512? Because 'alpha'
is fixed all the time and the list of patches and improvements is here
https://jenkins.pmmp.io/job/PocketMine-MP/changes. I really do not want to
go back only for one plugin :)
(sry for english, blame google trans.)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/RevivalPMMP/PureEntitiesX/issues/266#issuecomment-359139437>,
or mute the thread

**Comment by 95CivicSi** [comment]
Anyone having this problem, please test the following version:

https://poggit.pmmp.io/r/21487/PureEntitiesX_dev-197.phar

**Comment by Daniil129932** [comment]
Okay

26 янв. 2018 г. 9:14 AM пользователь "Aaron Salyer" <
notifications@github.com> написал:

**Comment by 95CivicSi** [comment]
Sorry for the confusion.  Please try this file:

https://poggit.pmmp.io/r/21488/PureEntitiesX_dev-198.phar

**Comment by 95CivicSi** [comment]
Last run, This should silence all errors related to API updates up to dev-657.

https://poggit.pmmp.io/r/21491/PureEntitiesX_dev-200.phar
