### ISSUE TITLE
Mobs not moving nor attacking

### ISSUE THREAD

**Issue by MidWolfhunter** [RevivalPMMP/PureEntitiesX#392]
I installed the latest version (0.6.3) of this plugin. I am on the updsted and most stable version of PocketMine. Regarding my issue, no longs are nessecary. I am experiencing mobs that do not move and attack such as monsters. I tried playing around with the config, but it seems not to work. 

My server  is running on 8 cores and has a total of 12GB RAM

**Comment by 95CivicSi** [comment]
So that you are aware, CPU core count has little impact on the performance of a single server instance.

I am not able to reproduce this error and need more details about your setup to help.  Please add the info requested in the template that was provided.  It may be easiest to open a new issue and fill out the template instead of deleting it.
