### ISSUE TITLE
Poggit is no longer working

### ISSUE THREAD

**Issue by Dog2puppy** [RevivalPMMP/PureEntitiesX#63]
Title says it all! Poggit is down.

**Comment by Sandertv** [comment]
I'm not sure yeah, sometimes the button does show up properly, sometimes it doesn't. @Magicode1 ! :P

**Comment by IgniteWhite** [comment]
Yes, I think it's not working.

**Comment by Dog2puppy** [comment]
It's caused by the switch to a real server, rather than being ran on @SOF3 computer.

**Comment by jasonwynn10** [comment]
until it becomes in working order again, we will just have to compile the plugins using the old fashioned method

**Comment by Magicode1** [comment]
I think we just need to re-enable it. Switching it to a VPS must have reset it.

**Comment by Dog2puppy** [comment]
@Magicode1 It did. I had to reenable mine.

**Comment by ivzakirov** [comment]
Hi everyone. Since poggit is down installation seems to be a bit complicated. I have installed it but pocketmine cant see it. Could you tell me please where is the problem? I wish to hide this into spoiler but cant realized how.

`user@host:~/repo/pmmp$ ls`
_banned-ips.txt      CONTRIBUTING.md  players                 pocketmine.yml  server.properties  start.sh        worlds_
_banned-players.txt  LICENSE          plugins                 README.md       src                tests
bin                 ops.txt          PocketMine-MP.phar.bal  server.log      start.cmd          white-list.txt_

`user@host:~/repo/pmmp$ cd plugins/`

`user@host:~/repo/pmmp/plugins$ git clone https://github.com/RevivalPMMP/PureEntitiesX.git`
_Cloning into 'PureEntitiesX'..._
_[...]_
_Checking connectivity... done._

`user@host:~/repo/pmmp/plugins$ cd PureEntitiesX/`

`user@host:~/repo/pmmp/plugins/PureEntitiesX$ git checkout V3.0-beta `
_Note: checking out 'V3.0-beta'._
_[...]_
_HEAD is now at a043489... Remove debug stuff._

`user@host:~/repo/pmmp/plugins/PureEntitiesX$ cd ../..`

`user@host:~/repo/pmmp$ ./start.sh `
_[12:54:45] [Server thread/WARNING]: Non-packaged PocketMine-MP installation detected, do not use on production._
_[...]_
_[12:54:45] [Server thread/INFO]: Done (0.643s)! For help, type "help" or "?"_
`plugins`
_[12:54:49] [Server thread/INFO]: Plugins (0):_

**Comment by archie426** [comment]
@ivzakirov Please open this in another issue

**Comment by archie426** [comment]
Also, poggit is not working for me either, might be worth submitting to issue tracker

**Comment by Magicode1** [comment]
I fixed it :)
